version: '2.15.1'
services:
  admin:
    build: 
      context: ./admin
    container_name: admin
    ports:
      - "3000:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    env_file:
      - ./admin/.env
    depends_on:
      - server
  client:
    build: 
      context: ./client
    container_name: client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - server
  server:
    build: 
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env